# Generated by Django 4.2.7 on 2023-12-09 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=255, verbose_name='Сценическое имя')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('sur_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('slug', models.SlugField(max_length=130, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Артист',
                'verbose_name_plural': 'Артисты',
                'ordering': ['nick_name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Стиль')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=130, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стили',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('bpm', models.FloatField(blank=True, null=True, verbose_name='Темп')),
                ('key', models.CharField(blank=True, max_length=16, null=True, verbose_name='Тональность')),
                ('lyrics', models.TextField(blank=True, null=True, verbose_name='Слова')),
                ('chords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Аккорды')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год релиза')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='song_covers/', verbose_name='Обложка')),
                ('additional', models.TextField(blank=True, default='<strong>Закольцованность припева:</strong> <br><strong>Диапазон:</strong>', null=True, verbose_name='Дополнительная информация')),
                ('slug', models.SlugField(max_length=130, unique=True, verbose_name='Слаг')),
                ('authors', models.ManyToManyField(blank=True, related_name='author_songs', to='main.artist', verbose_name='Авторы')),
                ('composers', models.ManyToManyField(blank=True, related_name='composer_songs', to='main.artist', verbose_name='Композиторы')),
                ('genres', models.ManyToManyField(blank=True, related_name='genre_songs', to='main.genre', verbose_name='Стили')),
                ('performers', models.ManyToManyField(blank=True, related_name='performer_songs', to='main.artist', verbose_name='Исполнители')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('songs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='main.song', verbose_name='Песня')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='ArtistImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artist_images/', verbose_name='Изображения')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.artist', verbose_name='Артист')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата релиза')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='album_covers/', verbose_name='Обложка')),
                ('slug', models.SlugField(max_length=130, unique=True, verbose_name='Слаг')),
                ('artist', models.ManyToManyField(related_name='albums', to='main.artist', verbose_name='Исполнители')),
                ('songs', models.ManyToManyField(blank=True, related_name='albums', to='main.song', verbose_name='Песни')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
    ]
