# Generated by Django 4.2.7 on 2023-11-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artist_images/', verbose_name='Изображения')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='NickName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('bpm', models.FloatField(blank=True, null=True, verbose_name='bpm')),
                ('key', models.CharField(blank=True, max_length=3, null=True, verbose_name='Тональность')),
                ('lyrics', models.TextField(blank=True, null=True, verbose_name='Слова')),
                ('chords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Аккорды')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата релиза')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='song_covers/', verbose_name='Обложка')),
                ('genre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Стиль')),
                ('author', models.ManyToManyField(blank=True, related_name='authors', to='main.artist', verbose_name='Автор')),
                ('composer', models.ManyToManyField(blank=True, related_name='composers', to='main.artist', verbose_name='Композитор')),
                ('links', models.ManyToManyField(blank=True, related_name='songs', to='main.link', verbose_name='Ссылка')),
                ('performer', models.ManyToManyField(blank=True, related_name='performers', to='main.artist', verbose_name='Исполнитель')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='images', to='main.artistimage', verbose_name='Изображения'),
        ),
        migrations.AddField(
            model_name='artist',
            name='nick_names',
            field=models.ManyToManyField(blank=True, related_name='nicks', to='main.nickname', verbose_name='Псевдонимы'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата релиза')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='album_covers/', verbose_name='Обложка')),
                ('artist', models.ManyToManyField(related_name='albums', to='main.artist', verbose_name='Исполнители')),
                ('songs', models.ManyToManyField(blank=True, related_name='albums', to='main.song', verbose_name='Песни')),
            ],
        ),
    ]
