# Generated by Django 4.2.7 on 2023-11-21 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='links',
        ),
        migrations.AddField(
            model_name='link',
            name='songs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.song', verbose_name='Песня'),
        ),
    ]
