# Generated by Django 4.2.7 on 2023-12-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='additional',
            field=models.TextField(blank=True, default='<strong>Закольцованность припева:</strong> <br><strong>Гармонии куплета и припева:</strong> <br><strong>Диапазон:</strong>', null=True, verbose_name='Дополнительная информация'),
        ),
    ]
