# Generated by Django 4.2.7 on 2023-11-21 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_song_links_link_songs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
        migrations.RemoveField(
            model_name='artist',
            name='nick_names',
        ),
        migrations.AddField(
            model_name='nickname',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.artist', verbose_name='Артист'),
        ),
    ]
