# Generated by Django 4.2.7 on 2023-11-21 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_song_options_remove_artist_nick_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='image',
        ),
        migrations.AddField(
            model_name='artistimage',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.artist', verbose_name='Артист'),
        ),
    ]
