# Generated by Django 4.2.7 on 2023-11-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_album_options_alter_artist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='performer',
            field=models.ManyToManyField(blank=True, related_name='performers', related_query_name='performers', to='main.artist', verbose_name='Исполнитель'),
        ),
    ]
