# Generated by Django 4.2.7 on 2023-11-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_song_performer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='performer',
            field=models.ManyToManyField(blank=True, related_name='performers', to='main.artist', verbose_name='Исполнитель'),
        ),
    ]
