# Generated by Django 4.2.7 on 2023-11-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_song_performer'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='additional',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
    ]
