# Generated by Django 4.2.7 on 2023-11-25 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_song_additional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='author',
        ),
        migrations.RemoveField(
            model_name='song',
            name='composer',
        ),
        migrations.RemoveField(
            model_name='song',
            name='performer',
        ),
        migrations.AddField(
            model_name='song',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='author_songs', to='main.artist', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='song',
            name='composers',
            field=models.ManyToManyField(blank=True, related_name='composer_songs', to='main.artist', verbose_name='Композитор'),
        ),
        migrations.AddField(
            model_name='song',
            name='performers',
            field=models.ManyToManyField(blank=True, related_name='performer_songs', to='main.artist', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='link',
            name='songs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='links', to='main.song', verbose_name='Песня'),
        ),
    ]
