# Generated by Django 4.2.7 on 2023-11-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_song_options_artist_nick_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='nick_name',
            field=models.CharField(max_length=255, verbose_name='Сценическое имя'),
        ),
    ]
