# Generated by Django 4.2.7 on 2023-11-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_artist_nick_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['nick_name'], 'verbose_name': 'Артист', 'verbose_name_plural': 'Артисты'},
        ),
        migrations.AlterField(
            model_name='song',
            name='additional',
            field=models.TextField(blank=True, default='Закольцованность припева:\nДиапазон', null=True, verbose_name='Дополнительная информация'),
        ),
    ]
