# Generated by Django 4.2.7 on 2023-11-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_artist_options_alter_song_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='additional',
            field=models.TextField(blank=True, default='Закольцованность припева: \nДиапазон: ', null=True, verbose_name='Дополнительная информация'),
        ),
    ]
