# Generated by Django 4.2.7 on 2023-11-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_song_additional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
        migrations.AlterField(
            model_name='song',
            name='key',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Тональность'),
        ),
    ]
