# Generated by Django 4.2.7 on 2023-11-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_song_author_order_song_composer_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='performer_order',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Порядок исполнителей'),
        ),
    ]
