# Generated by Django 4.2.7 on 2023-11-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_song_performer_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='performer_order',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Порядок исполнителей'),
        ),
    ]
