# Generated by Django 4.2.7 on 2023-11-28 04:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_song_performer_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='author_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='Порядок авторов'),
        ),
        migrations.AlterField(
            model_name='song',
            name='composer_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='Порядок композиторов'),
        ),
        migrations.AlterField(
            model_name='song',
            name='performer_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='Порядок исполнителей'),
        ),
    ]
