# Generated by Django 4.2.7 on 2023-11-29 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_song_author_order_alter_song_composer_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Стиль')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True, verbose_name='Слаг')),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='song',
            name='release_date',
        ),
        migrations.AddField(
            model_name='song',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год релиза'),
        ),
        migrations.AlterField(
            model_name='artistimage',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.artist', verbose_name='Артист'),
        ),
        migrations.AlterField(
            model_name='song',
            name='bpm',
            field=models.FloatField(blank=True, null=True, verbose_name='Темп'),
        ),
        migrations.AddField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='genre_songs', to='main.genre', verbose_name='Стили'),
        ),
    ]
