# Generated by Django 4.2.7 on 2023-11-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_genre_remove_song_genre_remove_song_release_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Стиль', 'verbose_name_plural': 'Стили'},
        ),
    ]
