# Generated by Django 4.2.7 on 2023-11-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_genre_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(default='', max_length=130, verbose_name='Слаг'),
        ),
    ]
