# Generated by Django 4.2.7 on 2023-11-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_song_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default='', max_length=130, unique=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='', max_length=130, unique=True, verbose_name='Слаг'),
        ),
    ]
