# Generated by Django 4.2.7 on 2023-11-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_album_slug_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(default='', max_length=130, verbose_name='Слаг'),
        ),
    ]
