# Generated by Django 4.2.7 on 2023-12-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_genre_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='url',
        ),
    ]
